# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-28 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('errcode', models.IntegerField()),
                ('oc_id', models.IntegerField()),
                ('oc_ip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('hash_value', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('domain', models.CharField(max_length=50)),
                ('create_time', models.DateField()),
                ('start_time', models.DateField()),
                ('success_rate_1st', models.IntegerField()),
                ('success_time_1st', models.DateField()),
                ('success_rate_2nd', models.IntegerField()),
                ('success_time_2nd', models.DateField()),
                ('errorMsg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuerySimpleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_1st_d', models.IntegerField()),
                ('time_1st_s', models.IntegerField()),
                ('time_2nd_d', models.IntegerField()),
                ('time_2nd_s', models.IntegerField()),
                ('isError', models.BooleanField()),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QueryResult')),
            ],
        ),
        migrations.AddField(
            model_name='failedoc',
            name='qr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QueryResult'),
        ),
    ]
