# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-28 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysimpleresult',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querysimpleresult',
            name='task_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
